# IPL Win Predictor

### Import necessary libraries

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

### Load the dataset

In [2]:
match_data = pd.read_csv("Desktop/IPL Win Predictor/match_data.csv",low_memory=False)
match_info = pd.read_csv("Desktop/IPL Win Predictor/match_info_data.csv",low_memory=False)

In [3]:
match_info.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit

In [4]:
match_data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,over,ball.1
0,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353,0,1.0
1,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353,0,2.0
2,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353,0,3.0
3,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353,0,4.0
4,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353,0,5.0

### Rename column to merge both datasets

In [5]:
match_info.rename(columns={"id": "match_id"}, inplace=True)
df = match_data.merge(match_info,on="match_id")

In [6]:
df.columns

Index(['match_id', 'season_x', 'start_date', 'venue_x', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'cricsheet_id', 'over', 'ball.1', 'season_y',
       'city', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision',
       'result', 'dl_applied', 'winner', 'win_by_runs', 'win_by_wickets',
       'player_of_match', 'venue_y', 'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [7]:
df['total_runs'] = df['runs_off_bat'] + df['extras']

In [8]:
df.head()

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3,total_runs
0,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0
1,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0
2,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1
3,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1
4,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1

In [9]:
df.shape

(243817, 43)

### Adding all runs of each inning

In [10]:
df.groupby(['match_id','innings']).sum()['total_runs']

match_id  innings
335982    1          222
          2           82
335983    1          240
          2          207
335984    1          129
                    ...
1370351   2          101
1370352   1          233
          2          171
1370353   1          214
          2          171
Name: total_runs, Length: 2075, dtype: int64

### Add  +1  in all first inning runs for total runs which is target

In [11]:
total_score_df = df.groupby(['match_id','innings']).sum()['total_runs'].reset_index()
total_score_df = total_score_df[total_score_df['innings'] == 1]
total_score_df["total_runs"] = total_score_df["total_runs"] + 1

In [12]:
total_score_df

      match_id  innings  total_runs
0       335982        1         223
2       335983        1         241
4       335984        1         130
6       335985        1         166
8       335986        1         111
...        ...      ...         ...
2065   1359544        1         198
2067   1370350        1         173
2069   1370351        1         183
2071   1370352        1         234
2073   1370353        1         215

[1024 rows x 3 columns]

### New column for total runs which is target

In [13]:
df = df.merge(total_score_df[['match_id','total_runs']],left_on='match_id',right_on='match_id')

In [14]:
df

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3,total_runs_x,total_runs_y
0,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215
1,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215
2,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,215
3,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,215
4,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.5,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223
243813,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.6,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223
243814,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.7,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,0,223
243815,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,15.1,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223
243816,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,15.2,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,0,223

In [15]:
df['batting_team'].unique()

array(['Gujarat Titans', 'Chennai Super Kings', 'Mumbai Indians',
       'Lucknow Super Giants', 'Sunrisers Hyderabad',
       'Royal Challengers Bangalore', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Punjab Kings', 'Rajasthan Royals',
       'Kings XI Punjab', 'Delhi Daredevils', 'Rising Pune Supergiant',
       'Gujarat Lions', 'Rising Pune Supergiants', 'Pune Warriors',
       'Deccan Chargers', 'Kochi Tuskers Kerala'], dtype=object)

### 'Kochi Tuskers Kerala', 'Rising Pune Supergiants' and 'Pune Warriors' are old teams and not playing in IPL 2024

In [16]:
teams = [
    'Gujarat Titans',
    'Mumbai Indians',
    'Chennai Super Kings',
    'Lucknow Super Giants'
    'Rajasthan Royals',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Sunrisers Hyderabad',
    'Punjab Kings',
    'Delhi Capitals'
]

### Same teams with two diffrent names

In [17]:
df['batting_team'] = df['batting_team'].str.replace('Gujarat Lions','Gujarat Titans')
df['bowling_team'] = df['bowling_team'].str.replace('Gujarat Lions','Gujarat Titans')

df['batting_team'] = df['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
df['bowling_team'] = df['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')

df['batting_team'] = df['batting_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
df['bowling_team'] = df['bowling_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

df['batting_team'] = df['batting_team'].str.replace('Kings XI Punjab','Punjab Kings')
df['bowling_team'] = df['bowling_team'].str.replace('Kings XI Punjab','Punjab Kings')

In [18]:
df = df[df['batting_team'].isin(teams)]
df = df[df['bowling_team'].isin(teams)]

In [19]:
df

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3,total_runs_x,total_runs_y
0,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215
1,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215
2,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,215
3,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,215
4,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.5,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223
243813,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.6,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223
243814,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.7,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,0,223
243815,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,15.1,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223
243816,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,15.2,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,0,223

### Rain interrupted matches

In [20]:
df['dl_applied'].value_counts()

dl_applied
0    166430
1      2589
Name: count, dtype: int64

### Only second innings to chase the runs

In [21]:
df = df[df['innings'] == 2]

### Cumulative runs of each second inning

In [22]:
df.groupby('match_id')['total_runs_x'].cumsum()

122        0
123        0
124        4
125        6
126        6
          ..
243812    80
243813    81
243814    81
243815    82
243816    82
Name: total_runs_x, Length: 81544, dtype: int64

### Current score of each ball

In [23]:
df['current_score'] = df.groupby('match_id')['total_runs_x'].cumsum()

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\819011198.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['total_runs_x'].cumsum()

### Runs left to chase and win the match

In [24]:
df['runs_left'] = df['total_runs_y'] - df['current_score']

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\2631345789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['runs_left'] = df['total_runs_y'] - df['current_score']

In [25]:
df.columns

Index(['match_id', 'season_x', 'start_date', 'venue_x', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'cricsheet_id', 'over', 'ball.1', 'season_y',
       'city', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision',
       'result', 'dl_applied', 'winner', 'win_by_runs', 'win_by_wickets',
       'player_of_match', 'venue_y', 'umpire1', 'umpire2', 'umpire3',
       'total_runs_x', 'total_runs_y', 'current_score', 'runs_left'],
      dtype='object')

### Balls left

In [26]:
df['balls_left'] = 120 - (df['over']*6 + df['ball.1'])

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\1714369084.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = 120 - (df['over']*6 + df['ball.1'])

In [27]:
df

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,player_of_match,venue_y,umpire1,umpire2,umpire3,total_runs_x,total_runs_y,current_score,runs_left,balls_left
122,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.1,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215,0,215,119.0
123,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.2,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215,0,215,118.0
124,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.3,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4,215,4,211,117.0
125,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.4,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2,215,6,209,116.0
126,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.5,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215,6,209,115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.5,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223,80,143,31.0
243813,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.6,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223,81,142,30.0
243814,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,14.7,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,0,223,81,142,29.0
243815,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,15.1,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,1,223,82,141,29.0
243816,335982,2007/08,18-04-2008,M Chinnaswamy Stadium,2,15.2,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,0,223,82,141,28.0

### Cumulative wickets of each second inning

In [28]:
df['player_dismissed'] = df['player_dismissed'].fillna("0")
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:x if x == "0" else "1")
df['player_dismissed'] = df['player_dismissed'].astype('int')

wickets = df.groupby('match_id')['player_dismissed'].cumsum()
df['wickets'] = 10 - wickets
df.head()

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\1805967560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].fillna("0")
C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\1805967560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].apply(lambda x:x if x == "0" else "1")
C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\1805967560.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].astype('int')
C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\1805967560.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets'] = 10 - wickets

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,venue_y,umpire1,umpire2,umpire3,total_runs_x,total_runs_y,current_score,runs_left,balls_left,wickets
122,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.1,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215,0,215,119.0,10
123,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.2,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215,0,215,118.0,10
124,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.3,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4,215,4,211,117.0,10
125,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.4,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2,215,6,209,116.0,10
126,1370353,2023,29-05-2023,"Narendra Modi Stadium, Ahmedabad",2,0.5,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,0,215,6,209,115.0,10

### Current run rate = runs/overs

In [29]:
df['crr'] = (df['current_score']*6)/(120 - df['balls_left'])

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\556160272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr'] = (df['current_score']*6)/(120 - df['balls_left'])

### Required run rate = runs left/balls left

In [30]:
df['rrr'] = (df['runs_left']*6)/df['balls_left']

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\611584998.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rrr'] = (df['runs_left']*6)/df['balls_left']

### Batting team wins or loses

In [31]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

### New column of batting team result

In [32]:
df['result'] = df.apply(result,axis=1)

C:\Users\rohit\AppData\Local\Temp\ipykernel_4560\3268034411.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['result'] = df.apply(result,axis=1)

### Final data frame

In [33]:
final_df = df[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_y','crr','rrr','result']]

In [34]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_y,crr,rrr,result
122,Chennai Super Kings,Gujarat Titans,Ahmedabad,215,119.0,10,215,0.000000,10.840336,1
123,Chennai Super Kings,Gujarat Titans,Ahmedabad,215,118.0,10,215,0.000000,10.932203,1
124,Chennai Super Kings,Gujarat Titans,Ahmedabad,211,117.0,10,215,8.000000,10.820513,1
125,Chennai Super Kings,Gujarat Titans,Ahmedabad,209,116.0,10,215,9.000000,10.810345,1
126,Chennai Super Kings,Gujarat Titans,Ahmedabad,209,115.0,10,215,7.200000,10.904348,1
...,...,...,...,...,...,...,...,...,...,...
243812,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,143,31.0,1,223,5.393258,27.677419,0
243813,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,142,30.0,1,223,5.400000,28.400000,0
243814,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,142,29.0,1,223,5.340659,29.379310,0
243815,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,141,29.0,1,223,5.406593,29.172414,0
243816,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,141,28.0,0,223,5.347826,30.214286,0

### Shuffling for better accuracy

In [35]:
final_df = final_df.sample(final_df.shape[0])

In [36]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_y,crr,rrr,result
20489,Punjab Kings,Delhi Capitals,Navi Mumbai,81,50.0,4,160,6.771429,9.720000,0
48421,Chennai Super Kings,Punjab Kings,Mumbai,56,71.0,9,107,6.244898,4.732394,1
20478,Punjab Kings,Delhi Capitals,Navi Mumbai,93,61.0,4,160,6.813559,9.147541,0
153693,Punjab Kings,Sunrisers Hyderabad,Chandigarh,80,42.0,6,151,5.461538,11.428571,0
33297,Chennai Super Kings,Punjab Kings,Mumbai,121,56.0,5,181,5.625000,12.964286,0
...,...,...,...,...,...,...,...,...,...,...
135406,Chennai Super Kings,Punjab Kings,Mumbai,98,58.0,7,227,12.483871,10.137931,0
74580,Punjab Kings,Chennai Super Kings,Chennai,126,90.0,8,161,7.000000,8.400000,0
64984,Chennai Super Kings,Mumbai Indians,Hyderabad,40,21.0,6,150,6.666667,11.428571,0
139988,Punjab Kings,Sunrisers Hyderabad,Hyderabad,14,14.0,6,206,10.867925,6.000000,0
22561,Sunrisers Hyderabad,Royal Challengers Bangalore,Mumbai,190,108.0,8,193,1.500000,10.555556,0

### Drop null values

In [37]:
final_df.dropna(inplace=True)

### Neglecting 0 ball left value to prevent infinite rrr

In [38]:
final_df = final_df[final_df['balls_left'] != 0]

### Train Test Split

In [39]:
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [40]:
X_train

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_y,crr,rrr
209661,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata,40,11.0,6,182,7.816514,21.818182
93741,Mumbai Indians,Kolkata Knight Riders,Bangalore,81,100.0,8,108,8.100000,4.860000
133868,Sunrisers Hyderabad,Chennai Super Kings,Chennai,205,118.0,10,210,15.000000,10.423729
12172,Royal Challengers Bangalore,Chennai Super Kings,Bengaluru,146,77.0,8,227,11.302326,11.376623
33744,Delhi Capitals,Gujarat Titans,Pune,148,100.0,9,172,7.200000,8.880000
...,...,...,...,...,...,...,...,...,...
109142,Gujarat Titans,Mumbai Indians,Kanpur,31,32.0,6,173,9.681818,5.812500
63751,Kolkata Knight Riders,Mumbai Indians,Abu Dhabi,55,8.0,2,196,7.553571,41.250000
192856,Punjab Kings,Mumbai Indians,Mumbai,155,103.0,9,160,1.764706,9.029126
218567,Royal Challengers Bangalore,Delhi Capitals,Johannesburg,118,94.0,9,135,3.923077,7.531915
85482,Mumbai Indians,Punjab Kings,Indore,119,64.0,9,175,6.000000,11.156250

### ColumnTransformer

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [43]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

### Train the model

In [44]:
pipe.fit(X_train,y_train)

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [45]:
y_pred = pipe.predict(X_test)

### Accuracy of the model

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8113170604359744

In [47]:
pipe.predict_proba(X_test)[584]

array([0.47785766, 0.52214234])

In [48]:
teams

['Gujarat Titans',
 'Mumbai Indians',
 'Chennai Super Kings',
 'Lucknow Super GiantsRajasthan Royals',
 'Royal Challengers Bangalore',
 'Kolkata Knight Riders',
 'Sunrisers Hyderabad',
 'Punjab Kings',
 'Delhi Capitals']

In [49]:
df['city'].unique()

array(['Ahmedabad', 'Chennai', 'Mumbai', 'Bengaluru', 'Delhi',
       'Hyderabad', 'Dharamsala', 'Kolkata', 'Chandigarh', 'Navi Mumbai',
       'Pune', 'Dubai', 'Sharjah', 'Abu Dhabi', nan, 'Visakhapatnam',
       'Indore', 'Bangalore', 'Kanpur', 'Rajkot', 'Raipur', 'Ranchi',
       'Cuttack', 'Nagpur', 'Johannesburg', 'Centurion', 'Durban',
       'Port Elizabeth', 'Bloemfontein', 'Kimberley', 'East London',
       'Cape Town'], dtype=object)

In [50]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [51]:
pickle.load(open('pipe.pkl','rb'))

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])